language: rust
rust:
- stable
- beta
- nightly
env:
- FEATURES=nightly
- FEATURES=
matrix:
  exclude:
  - rust: stable
    env: FEATURES=nightly
  - rust: beta
    env: FEATURES=nightly
script:
- cargo build --verbose --no-default-features --features="$FEATURES"
- cargo test --verbose --tests --no-default-features --features="$FEATURES"
- if [ "$FEATURES" = "nightly" ]; then RUSTFLAGS="--cfg docsrs" RUSTDOCFLAGS="--cfg docsrs" cargo test --verbose --doc; fi
