name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    env: 
      FEATURES: "${{ matrix.rust == 'nightly' && 'nightly' || '' }}"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --no-default-features --features="$FEATURES"
    - name: Tests
      run: cargo test --verbose --tests --no-default-features --features="$FEATURES"
    - name: Test doc
      run: cargo test --verbose --doc --no-default-features --features="$FEATURES"
    - name: Doc
      run: cargo doc --verbose --no-default-features --features="$FEATURES"
    - name: Test docsrs
      run: if [ "$FEATURES" = "nightly" ]; then RUSTFLAGS="--cfg docsrs" RUSTDOCFLAGS="--cfg docsrs" cargo test --verbose --doc; fi
    - name: Docsrs
      run: if [ "$FEATURES" = "nightly" ]; then RUSTFLAGS="--cfg docsrs" RUSTDOCFLAGS="--cfg docsrs" cargo doc --verbose; fi
